# Setup
name:         Anarcho-Software
tagline:      No gods, no masters, all unchecked errors are bastards
domain: kylie-sre.github.io
url: https://kylie-sre.github.io
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
